version: "3.9"

networks:
  incepnet:
    name: incepnet
    driver: bridge

volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bcaffere/data/wp

  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/bcaffere/data/db

  prt:
    name: prt
    driver: local
    driver_opts:
      type: none
      o: bind
      device: home/bcaffere/data/prt

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - incepnet

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file: .env
    volumes:
      - wp:/var/www/wordpress
    networks:
      - incepnet
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - wp:/var/www/wordpress
    networks:
      - incepnet
    depends_on:
      - wordpress
    ports:
      - "443:443"

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    restart: always
    env_file: .env
    networks:
      - incepnet
    depends_on:
      - nginx
    ports:
      - "6379:6379"

  # ftp-server:
  #   container_name: ftp-server
  #   build: ./requirements/bonus/ftp-server/
  #   restart: always
  #   env_file: .env
  #   volumes:
  #     - wp:/var/www/ftp
  #   networks:
  #     - incepnet
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "21:21"
  #     - "21000:21000"
  #     - "21001:21001"

  site:
    container_name: site
    build: requirements/bonus/site/
    restart: always
    networks:
      - incepnet
    depends_on:
      - nginx
    ports:
      - "1111:1111"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    restart: always
    depends_on:
      - mariadb
    networks:
      - incepnet
    ports:
      - "8080:8080"

  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer/
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - prt:/data
    restart: always
    depends_on:
      - wordpress
    networks:
      - incepnet
    ports:
      - "9443:9443"
